#!/usr/bin/env sh
[ "$POB_GIT_HOOKS" = "2" ] && set -x
[ "$POB_GIT_HOOKS" = "0" ] && exit 0
[ "$HUSKY" = "0" ] && exit 0

# z40 is the value matching the empty blob/commit/tree SHA (zero x 40)
z40=0000000000000000000000000000000000000000
branch_ref=$(git symbolic-ref HEAD)

while read local_ref local_sha remote_ref remote_sha
do
  # Skip if branch deletion
  if [ "$local_sha" != "$z40" ]; then
    if [ "$local_ref" = "$branch_ref" ]; then
      yarn run checks && yarn run lint && yarn test --run --changed origin/main
    fi
  fi
done
