defaultSemverRangePrefix: ^

enableGlobalCache: true

nodeLinker: node-modules

npmMinimalAgeGate: 4320

npmPreapprovedPackages:
  - "@pob/*"
  - alouette
  - alouette-icons
  - nightingale
  - nightingale-logger
