defaultSemverRangePrefix: ^
enableMessageNames: false
nodeLinker: node-modules
plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"
supportedArchitectures:
  cpu:
    - x64
    - arm64
  os:
    - linux
    - darwin
yarnPath: .yarn/releases/yarn-3.6.2.cjs
