defaultSemverRangePrefix: ^
enableMessageNames: false
nodeLinker: node-modules
plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"
  - path: .yarn/plugins/@yarnpkg/plugin-conventional-version.cjs
    spec: >-
      https://raw.githubusercontent.com/christophehurpeau/yarn-plugin-conventional-version/main/bundles/%40yarnpkg/plugin-conventional-version.cjs
supportedArchitectures:
  cpu:
    - x64
    - arm64
  os:
    - linux
    - darwin
yarnPath: .yarn/releases/yarn-3.6.4.cjs
