name: "Create documentation and deploy to Github pages"
on:
  push:
    branches:
      - main

jobs:
  create-documentation-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7

      - name: Install pnpm
        uses: pnpm/action-setup@v6
        with:
          version: 11

      - uses: actions/setup-node@v7
        with:
          node-version: 24

      - name: Install Dependencies
        run: pnpm install --frozen-lockfile

      - name: Run tsc for tsc cache
        run: pnpm tsc

      - name: Generate Typedoc
        run: pnpm typedoc --tsconfig tsconfig.doc.json

      - name: Create nojekyll
        run: touch docs/.nojekyll

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
