name: Push CI
permissions:
  contents: read
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v7

      - name: Install pnpm
        uses: pnpm/action-setup@v6
        with:
          version: 12

      - uses: actions/setup-node@v7
        with:
          node-version: 24

      - name: Install Dependencies
        run: pnpm install --frozen-lockfile

      - name: Build
        run: pnpm run build

      - name: Check nothing was forgotten before commit
        run: pnpm exec repository-check-dirty

  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v7

      - name: Install pnpm
        uses: pnpm/action-setup@v6
        with:
          version: 12

      - uses: actions/setup-node@v7
        with:
          node-version: 24

      - name: Install Dependencies
        run: pnpm install --frozen-lockfile

      - name: Format
        run: pnpm run format:check

      - name: Typescript
        run: pnpm run tsc

      - name: Eslint
        run: pnpm run lint:eslint

  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [22, 24]

    steps:
      - uses: actions/checkout@v7

      - name: Install pnpm
        uses: pnpm/action-setup@v6
        with:
          version: 12

      - uses: actions/setup-node@v7
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install Dependencies
        run: pnpm install --frozen-lockfile

      - name: Test
        run: pnpm run test
        if: matrix.node-version != 24

      - name: Generate Test Coverage
        run: pnpm run test:coverage:generate
        if: matrix.node-version == 24
        env:
          CI: true

      - name: Send results to codecov
        uses: codecov/codecov-action@v7
        if: matrix.node-version == 24 && github.actor != 'dependabot[bot]'
        with:
          fail_ci_if_error: true
          token: ${{ secrets.CODECOV_TOKEN }}
